### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by derrick-fleming** [derrick-fleming/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a list of Animal Crossing villagers.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to scroll through a list of different villager icons.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="650" alt="Screen Shot 2022-09-26 at 10 04 00 AM" src="https://user-images.githubusercontent.com/109825222/192337608-3457d462-0f3b-494a-a3f8-343b4f99f044.png">
<img width="472" alt="Screen Shot 2022-09-26 at 10 08 30 AM" src="https://user-images.githubusercontent.com/109825222/192338434-a6f629ba-8d6a-4b9b-a55b-b159e51557a6.png">
<img width="296" alt="Screen Shot 2022-09-26 at 10 04 43 AM" src="https://user-images.githubusercontent.com/109825222/192338453-794aaa11-594a-4d8e-9e66-dff3fec6da0f.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a div for the navigation Bar 
- [ ] Add title, home icon, and leaf icon 
- [ ] Create a div for scroll information
- [ ] Add heading and icons for scroll info
- [ ] Add a div [data-view = “villager-view”] for animal species 
- [ ] Create container for animal species 
- [ ] Add sample animal species names and “back to top” 
- [ ] Add sample data for villager images & text
- [ ] Style using CSS 
- [ ] Ensure pages look nice on both mobile-sized and desktop-sized screens
- [ ] Query the DOM for the species list div 
- [ ] Create a new XMLHttpRequest() and send 'GET' request to Animal Crossing API
- [ ] Add event listener to execute function when response is loaded 
- [ ] Check status of the object 
- [ ] Create a `div` element to store the animal species
- [ ] Create a `heading` tag and append it to the `div` element
  - [ ] Set the heading text content to match the species name
  - [ ] Loop through the JSON object and for each object: 
  - [ ] Set the heading text content to match the species name
  - [ ] Check the file name to indicate a new species. 
  - [ ] Create an `a` tag and set its content to be the image icon
  - [ ] Create another `a` tag and set its textContent to be the Villager's name 
  - [ ] Append the tags to the species `div` element 
  - [ ] Once reach a new species, append the previous species `div` to DOM tree and reset the species `div` 
  - [ ] Finish loop after about 30-50 entries
- [ ] Check that entries are loading successfully. 
- [ ] Add event listener to 'load more' button. Continue process of adding more villagers. 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
